# Generated by Django 5.1.6 on 2025-04-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_test_status_test_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.BooleanField(default=False, help_text='False = Upcoming, True = Completed'),
        ),
    ]
