# Generated by Django 5.1.6 on 2025-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_testattempt_testcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempt',
            name='student',
        ),
        migrations.RemoveField(
            model_name='testcode',
            name='student',
        ),
        migrations.AddField(
            model_name='testattempt',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testcode',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='testcode',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
